name: Release IOTracesCORE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build
      run: |
        dotnet publish IOTracesCORE/IOTracesCORE.csproj `
          -c Release `
          -r win-x64 `
          --self-contained `
          -o ./publish `
          /p:PublishSingleFile=true
          
    - name: Package
      run: |
        Compress-Archive -Path ./publish/* -DestinationPath ./IOTracesCORE.zip
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: IOTracesCORE.zip
        generate_release_notes: true
